"""empty message

Revision ID: c03cdb5e1711
Revises: c6be19e4996a
Create Date: 2020-07-13 19:10:32.452462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03cdb5e1711'
down_revision = 'c6be19e4996a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'shows', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'datetime')
    op.drop_column('shows', 'artist_id')
    # ### end Alembic commands ###
